#pragma once

#define WND_PARAM_X     500
#define WND_PARAM_Y     0

#define WND_PARAM_WIDTH     396
#define WND_PARAM_HIGTH      589

#define WND_PARAM_TITLE     "飞机大战"

#define MAPSIZE_BACKGROUND_WIDTH		380
#define MAPSIZE_BACKGROUND_HEIGH		550

#define MAPSIZE_PLAYERPLANE_WIDTH		60
#define MAPSIZE_PLAYERPLANE_HEIGH		60

#define MAPSIZE_GUUNER_WIDTH		6
#define MAPSIZE_GUUNER_HEIGH		9

#define MAPSIZE_FOEPLANESMA_WIDTH		34
#define MAPSIZE_FOEPLANESMA_HEIGH		    28

#define MAPSIZE_FOEPLANEMID_WIDTH			70
#define MAPSIZE_FOEPLANEMID_HEIGH		    90

#define MAPSIZE_FOEPLANEBIG_WIDTH			108
#define MAPSIZE_FOEPLANEBIG_HEIGH		    129

#define TIMER_BACKGROUND_MOVE_TIMERID      1
#define TIMER_BACKGROUND_MOVE_INTERVAL    200

#define TIMER_PLAYERPLANE_MOVE_TIMERID      2
#define TIMER_PLAYERPLANE_MOVE_INTERVAL    20
#define PLAYERPLANE_MOVE_STEP				5

#define TIMER_GUNNER_MOVE_TIMERID      3
#define TIMER_GUNNER_MOVE_INTERVAL    100
#define GUNNER_MOVE_STEP				8

#define TIMER_SEND_GUNNER_MOVE_TIMERID      4
#define TIMER_SEND_GUNNER_INTERVAL    800

#define TIMER_FOEBIG_CREATE_TIMERID      5
#define TIMER_FOEBIG_CREATE_INTERVAL    12000
#define FOEBIG_MOVE_STEP				5

#define TIMER_FOEMID_CREATE_TIMERID      6
#define TIMER_FOEMID_CREATE_INTERVAL    9000
#define FOEMID_MOVE_STEP				9

#define TIMER_FOESMA_CREATE_TIMERID      7
#define TIMER_FOESMA_CREATE_INTERVAL    6000
#define FOESMA_MOVE_STEP				14

#define TIMER_FOEPLANE_MOVE_TIMERID     8
#define TIMER_FOEPLANE_MOVE_INTERVAL     200

//定时检查敌人飞机是否撞击炮弹、玩家飞机
#define TIMER_CHECK_FOEPLANE_HIT_TIMERID    9
#define TIMER_CHECK_FOEPLANE_HIT_INTERVAL    20

//定时切换敌人飞机爆炸效果
#define TIMER_CHANGE_FOEPLANE_BOOM_TIMERID    10
#define TIMER_CHANGE_FOEPLANE_BOOM_INTERVAL    400


#define BLOOD_FOEPLANESMA     2
#define BLOOD_FOEPLANEMID      6
#define BLOOD_FOEPLANEBIG		 10

#define GUNNER_HURT					 2